# 项目信息配置
project:
  name: admin
  version: 1.0.0
  env: production

# WEB服务器配置
server:
  port: 7891

# session设置
session:
  # 过期时间(单位: ms)
  timeout: 1800000

spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://rm-2zenv0qunwv18r7gnso.mysql.rds.aliyuncs.com:3306/yudb?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=true&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: admin123
    password: Admin123

    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  # JSON返回配置
  jackson:
    # 默认时区
    time-zone: GMT+8
    # 默认日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 127.0.0.1
    port: 3389
    timeout: 300
    database: 1
    password: iahanx&1818a
    pool:
    minIdle: 1
    maxIdle: 10
    maxWait: 3
    maxActive: 8


# MyBatis配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

# Swagger配置
swagger:
  host:
  title: ${project.name}接口文档
  description: ${project.name}接口文档
  enabled: true
  # 禁用swagger时的重定向地址
  redirect-uri: /

# 日志配置
logback:
  level: INFO
  appender: ${project.env}
# dao层的日志设置为debug，方便查看sql
logging:
  level:
    com.ynzyq.yudbadmin.dao: debug

imageUrl: https://yudianbao.ynzyqpp.cn

AppID: wxddc50bdd420f553a
AppSecret: f83e421e861f3c8e0568f4f6d1c3c983

encryptKey: bCmrzQAYZvBoOF3Y

jinDie:
  userInfo: http://localhost:7006/jindie/userInfo